
# Minimal Mistakes theme
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site settings
title: "Rowan Dejardin"
subtitle: "Research Technician - Heather Corrie Palaeoecology Laboratory"
url: "https://rowandejardin.github.io"

# Masthead image
logo: "/assets/images/avatar.png"

# Favicon
favicon: "/assets/images/favicon.png"

# Author sidebar info
author:
  name: Rowan Dejardin
  bio: "Research Technician - Heather Corrie Palaeoecology Laboratory"
  avatar: "/assets/images/avatar.png"
  email: rowan.dejardin@bristol.ac.uk
  location: Bristol, UK
  

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:rowan.dejardin@bristol.ac.uk"
  since: "2026"

# Build settings
markdown: kramdown

# Include/exclude
include:
  - _pages
  - assets/images
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Hide xml feed
atom_feed:
  hide: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
